### ISSUE TITLE
Installing with node v6 fails

### ISSUE THREAD

**Issue by mikegleasonjr** [sprity/sprity-lwip#7]
Breaks https://github.com/sprity/sprity

```
$ npm install sprity-lwip --save-dev
npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.

> lwip@0.0.8 install <redacted>/node_modules/lwip
> node-gyp rebuild

  CXX(target) Release/obj.target/lwip_decoder/src/decoder/init.o
In file included from ../src/decoder/init.cpp:1:
In file included from ../src/decoder/decoder.h:13:
../node_modules/nan/nan.h:590:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:596:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:601:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:607:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
4 errors generated.
```

**Comment by MKHenson** [comment]
Hey guys. any news on this? @chadwatson

**Comment by message** [comment]
@MKHenson Add shrinkwrap to your root https://gist.github.com/AubreyHewes/7ec769bd37d2d2ff9649f71a19ded57e

**Comment by intellix** [comment]
lwip 0.0.9 works here btw

**Comment by adgoncal** [comment]
`npm i` completed, but gulp task fails

> Error: PluggableError: lwip not found.

npm -v

> 2.15.8

node -v

> v4.4.7

CentOS Linux release 7.2.1511

lwip 0.0.9 did not work either.

---

Note: Everything works in node 0.12.4, but I need to upgrade to LTS.

**Comment by mikegleasonjr** [comment]
Please bump lwip to 0.0.9

**Comment by swarthy** [comment]
+1

**Comment by qkdreyer** [comment]
Current workaround : 
`
npm install -g https://github.com/chadwatson/sprity-lwip
`
